DROP SEQUENCE BED;
DROP SEQUENCE CATEG_ROOM;
DROP SEQUENCE ADDRESS;
DROP SEQUENCE HOTEL;
DROP SEQUENCE ROOM;
DROP SEQUENCE GUEST;
DROP SEQUENCE GUEST_RESERVATION;
DROP SEQUENCE HOTEL_RESERVATION;