-- ============================================================================
-- file : h2r-seq.sql
-- author : Noah PAULMIER / Noé LETEURTRE
-- date : 10/02/25
-- role : Creating sequences in the database
-- ============================================================================

CREATE SEQUENCE seq_ADDRESS
INCREMENT BY 1
START WITH 1
MINVALUE 0
NOCYCLE
CACHE 25;


CREATE SEQUENCE seq_BED
INCREMENT BY 1
START WITH 1
MINVALUE 0
NOCYCLE
CACHE 25;

CREATE SEQUENCE seq_GUEST
INCREMENT BY 1
START WITH 1
MINVALUE 0
NOCYCLE
CACHE 25;

CREATE SEQUENCE seq_GUEST_RESERVATION
INCREMENT BY 1
START WITH 1
MINVALUE 0
NOCYCLE
CACHE 25;

CREATE SEQUENCE seq_HOTEL
INCREMENT BY 1
START WITH 1
MINVALUE 0
NOCYCLE
CACHE 25;

CREATE SEQUENCE seq_HOTEL_RESERVATION
INCREMENT BY 1
START WITH 1
MINVALUE 0
NOCYCLE
CACHE 25;

CREATE SEQUENCE seq_ROOM
INCREMENT BY 1
START WITH 1
MINVALUE 0
NOCYCLE
CACHE 25;

